version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: andrew71
      MYSQL_DATABASE: taskself
      MYSQL_USER: andmaia
      MYSQL_PASSWORD: A@ndrew71
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - custom_network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskself?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: andmaia
      SPRING_DATASOURCE_PASSWORD: A@ndrew71
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge